pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=owasp_scan
      - check-success=Bandit
      - check-success=Analyze (python)
    actions:
      merge:
        method: merge
