version: '3.8'

services:
  nutmegplayground:
    image: nutmegplayground
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
  sut:
    image: python
    volumes:
      - $PWD:/app
    working_dir: /app
    command: sh -c "pip install pytest requests && pytest tests/end_to_end_test.py"
    depends_on: 
      - nutmegplayground
    environment:
      - BASE_URL=http://nutmegplayground
